"""add_timesheet_models

Revision ID: 8146a4d2305d
Revises: 9ff736e5ebf0
Create Date: 2026-07-17 23:13:52.682522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8146a4d2305d'
down_revision: Union[str, None] = '9ff736e5ebf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('period_start_date', sa.DateTime(), nullable=False),
    sa.Column('period_end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='timesheetstatus'), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_candidate_id'), 'timesheet', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_timesheet_id'), 'timesheet', ['id'], unique=False)
    op.create_table('timesheetentry',
    sa.Column('timesheet_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('hours_worked', sa.Float(), nullable=False),
    sa.Column('task_description', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheetentry_id'), 'timesheetentry', ['id'], unique=False)
    op.create_index(op.f('ix_timesheetentry_timesheet_id'), 'timesheetentry', ['timesheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheetentry_timesheet_id'), table_name='timesheetentry')
    op.drop_index(op.f('ix_timesheetentry_id'), table_name='timesheetentry')
    op.drop_table('timesheetentry')
    op.drop_index(op.f('ix_timesheet_id'), table_name='timesheet')
    op.drop_index(op.f('ix_timesheet_candidate_id'), table_name='timesheet')
    op.drop_table('timesheet')
    # ### end Alembic commands ###
