"""update_timesheet_status_and_review_fields

Revision ID: 974ee1ae369d
Revises: 8146a4d2305d
Create Date: 2026-07-17 23:28:31.921337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974ee1ae369d'
down_revision: Union[str, None] = '8146a4d2305d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheet', sa.Column('reviewed_by_id', sa.UUID(), nullable=True))
    op.add_column('timesheet', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('timesheet', sa.Column('approval_comments', sa.Text(), nullable=True))
    op.create_index(op.f('ix_timesheet_reviewed_by_id'), 'timesheet', ['reviewed_by_id'], unique=False)
    op.create_foreign_key(None, 'timesheet', 'user', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timesheet', type_='foreignkey')
    op.drop_index(op.f('ix_timesheet_reviewed_by_id'), table_name='timesheet')
    op.drop_column('timesheet', 'approval_comments')
    op.drop_column('timesheet', 'reviewed_at')
    op.drop_column('timesheet', 'reviewed_by_id')
    # ### end Alembic commands ###
