"""add_audit_log_and_version_fields

Revision ID: b72638c805b7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-18 23:36:51.742822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72638c805b7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheetauditlog',
    sa.Column('timesheet_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('submitted', 'resubmitted', 'shared', 'client_approved', 'client_rejected', 'finance_approved', 'finance_rejected', name='timesheetauditaction'), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheetauditlog_actor_id'), 'timesheetauditlog', ['actor_id'], unique=False)
    op.create_index(op.f('ix_timesheetauditlog_id'), 'timesheetauditlog', ['id'], unique=False)
    op.create_index(op.f('ix_timesheetauditlog_timesheet_id'), 'timesheetauditlog', ['timesheet_id'], unique=False)
    op.add_column('timesheet', sa.Column('current_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('timesheetentry', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheetentry', 'version')
    op.drop_column('timesheet', 'current_version')
    op.drop_index(op.f('ix_timesheetauditlog_timesheet_id'), table_name='timesheetauditlog')
    op.drop_index(op.f('ix_timesheetauditlog_id'), table_name='timesheetauditlog')
    op.drop_index(op.f('ix_timesheetauditlog_actor_id'), table_name='timesheetauditlog')
    op.drop_table('timesheetauditlog')
    # ### end Alembic commands ###
