"""Add invoice schema enhancements

Revision ID: f1d8e1ab65c8
Revises: b72638c805b7
Create Date: 2026-07-19 00:42:11.542763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d8e1ab65c8'
down_revision: Union[str, None] = 'b72638c805b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoiceauditlog',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('generated', 'updated', 'status_changed', 'sent', 'payment_received', name='invoiceauditaction'), nullable=False),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoiceauditlog_actor_id'), 'invoiceauditlog', ['actor_id'], unique=False)
    op.create_index(op.f('ix_invoiceauditlog_id'), 'invoiceauditlog', ['id'], unique=False)
    op.create_index(op.f('ix_invoiceauditlog_invoice_id'), 'invoiceauditlog', ['invoice_id'], unique=False)
    op.add_column('invoice', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('invoice', sa.Column('template_name', sa.String(length=50), server_default='default', nullable=False))
    op.add_column('invoice', sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Handle Enum migration manually
    op.execute("ALTER TABLE invoice ALTER COLUMN status TYPE VARCHAR")
    op.execute("UPDATE invoice SET status = 'ready' WHERE status = 'generated'")
    op.execute("DROP TYPE invoicestatus")
    
    invoice_status_enum = sa.Enum('draft', 'ready', 'sent', 'payment_pending', 'paid', name='invoicestatus')
    invoice_status_enum.create(op.get_bind())
    op.execute("ALTER TABLE invoice ALTER COLUMN status TYPE invoicestatus USING status::text::invoicestatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'snapshot_data')
    op.drop_column('invoice', 'template_name')
    op.drop_column('invoice', 'currency')
    op.drop_index(op.f('ix_invoiceauditlog_invoice_id'), table_name='invoiceauditlog')
    op.drop_index(op.f('ix_invoiceauditlog_id'), table_name='invoiceauditlog')
    op.drop_index(op.f('ix_invoiceauditlog_actor_id'), table_name='invoiceauditlog')
    op.drop_table('invoiceauditlog')
    # ### end Alembic commands ###
